apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    url: db:5432
    database: postgres
    user: postgres
    sslmode: disable
    jsonData:
      sslmode: disable
    secureJsonData:
      password: "postgres"